fix(package): remove `to-pascal-case` from peer dependencies
moneytree/mt-web-icons pull request #24
Opened 2019-07-03 05:35 UTC by mt-roberto

2019-07-03 05:38 UTC, mt-max commented on package.json
> +    "react": "^16.8.6"
Move the `react` from `dependencies` to `devDependencies` (use to develop), `peerDependencies` (use for build)  will be useless if it is already in `dependencies`.

2019-07-03 05:44 UTC, mt-micky requested changes
Please remove all unnecessary module from `dependencies`

2019-07-03 07:50 UTC, mt-micky commented on package.json
>    "scripts": {
Note: Could add a hook for `precommit` or `version` to build and add to commit

2019-07-03 07:54 UTC, mt-micky commented on package.json
> +  "main": "react/Icon/index.js",
You probably wanna add the path to your definition files as well:
`"types": "react/Icon//index.d.ts"`?

2019-07-03 12:12 UTC, mt-micky commented on package.json
>    "scripts": {
No, but you can do it in it
For example: `”precommit”: “yarn build && git add dist”,`

2019-07-04 07:48 UTC, mt-micky commented on README.md
> +import IconAuto from 'mt-web-icons/react/Auto';
```suggestion
import { Auto } from 'mt-web-icons';
```

2019-07-04 07:54 UTC, mt-micky approved these changes
Let’s release and give it a good try

2019-07-04 07:55 UTC, merged